### ISSUE TITLE
stream

### ISSUE THREAD

**Issue by kaue** [jasonbio/reddit-shell#4]
Its possible to include a stream option for new posts? =)

**Comment by jasonbio** [comment]
![image](https://cloud.githubusercontent.com/assets/9797854/9967019/0f42754a-5df5-11e5-82ed-0cc83eda79cb.png)

Anything is possible :D! A "watch" command could easily be implemented, what sort of interval between checks were you thinking? I wonder how reddit decides their rate-limit too, although I don't think reddit shell is close to hitting it. Still something to consider.

**Comment by kaue** [comment]
@jasonbio hahaha awesome! 

I think checking every x seconds would be perfect.

**Comment by jasonbio** [comment]
Sorry, just getting around to this now. New command added "watch [subreddit]". It will poll the specified subreddit every 15 seconds for new posts and echo them as they come in. Typing any other command will stop the watch process.

Commit: b4c44db2d318c210d14f63b60b548af5a4a732a5
