### ISSUE TITLE
Easter egg too awesome

### ISSUE THREAD

**Issue by themistymay** [jasonbio/reddit-shell#5]
Your xkcd/Jurassic Park easter egg is too awesome, I'm having a hard time comprehending my excitement.

PLZ FIX URRRR MURRRR GURRRRD

**Comment by jasonbio** [comment]
:D haha thanks. 

> PLZ FIX URRRR MURRRR GURRRRD

Did you have an issue to report with it or were you just leaving a comment?

**Comment by themistymay** [comment]
Just a comment of your awesomeness. Feel free to close this :+1:

**Comment by jasonbio** [comment]
Thanks :)
