### ISSUE TITLE
Implement as ssh server

### ISSUE THREAD

**Issue by Marak** [jasonbio/reddit-shell#6]
Just some food for thought.

You could build this as an actual terminal application, use https://github.com/chjj/term.js/ to serve it to the web, and then provide an SSH interface that users could SSH into to use the terminal app remotely.

I've used this pattern before for these types of applications and it works well.

**Comment by LaurentFough** [comment]
I like this idea.
May take on the challenge.

**Comment by jasonbio** [comment]
Hmm interesting. Wouldn't most users prefer to run something locally though rather than remotely, especially when accessing from their own environment?

**Comment by Marak** [comment]
Implementing client as SSH server requires you build Command Line Tool and serve it remotely. It's a remote SSH interface to a CLI tool that lives on server.

If you have the Command Line Tool built, you can just as easily install it locally and run from your own command line.

That is beauty of idea. Instead building JavaScript DOM code, you build CLI tool and expose it via web and ssh and local download.

**Comment by Marak** [comment]
To give you an idea, if you built a CLI tool, the SSH interface to serve it is about 20 lines of bash.

**Comment by Marak** [comment]
And the web interface is about 10 lines of javascript stream wrappers to term.js project

**Comment by jasonbio** [comment]
Decided not to do this, closing the issue
