### ISSUE TITLE
Add functionality -- create posts 

### ISSUE THREAD

**Issue by asadw1** [jasonbio/reddit-shell#9]
Is there already built-in functionality to create new links/text posts once a user is logged in? I was thinking to pull down a copy of this and add the functionality if you think it's a good idea!

**Comment by jasonbio** [comment]
Currently no, all you can do as a logged in user is comment on posts, reply to comments, and upvote/downvote posts. I'm really busy right now with other work so if you want to take a shot, go for it!

**Comment by asadw1** [comment]
Nice! I'll get started on this.
